# Site settings 配置站点
title: 'Four && Casper'
description: '自家的博客，没啥好说的。技术，情感分析，爱情导师，厨子，旅行。'
keywords: '关键词啥的最重要了,技术,情感分析,爱情导师,厨子,旅行'
url: 'https://wjmwjmwb.github.io'

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于我们: '/about.html'
  王者小分队: '/friendLink.html'

# 博主
author: true
name: 'Four And Casper'
NickName: 'Four && Casper'
webtitle: 'DM️'
bio: '四哥 && 四嫂'
about: true
aboutyou: '虽然现在工作在后端，但是依旧很喜欢iOS。虽然成了一个180斤的胖子，但是依旧很喜欢撸铁。虽然肥宅，但是依旧有个漂亮苗条爱旅行的媳妇。'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['facebook', 'weibo', 'QQ', 'github', 'Dribbble', 'twitter', 'instagram', 'weixin']
  mail: 'fourjob@yeah.net'
  weixin: '../assets/wx_qrcode.JPG' # your wechat image file path
  QQ: '../assets/qq_qrcode.JPG' # your QQ image file path
  weibo: 'https://weibo.com/2446857363/'
#  instagram: ''
#  twitter: ''
  github: 'https://github.com/wjmwjmwb'
#  Dribbble: ''
#  facebook: ''
#  Google: ''
#  zhihu: ''
#  juejin: ''
#  twitch: ''

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 王者小分队
friends:
  LanceGin: 'http://lancegin.cc'
  月下之光: 'https://www.celerysoft.com'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zOTgwMS8xNjMyOA==' # MTAyMC8zOTgwMS8xNjMyOA==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: 'http://wjmwjmwb.com'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
